[package]
name = "algorithm"
version = "0.1.0"
authors = ["near129"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-snippet = "0.6"
rand = { version = "=0.7.3", features = ["small_rng"] }